### ISSUE TITLE
Internationalization - i18n

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#10]
Currently we do not use i18n, but we have to setup the user preferences and output localized strings.

Before we just start to copy paste the current language files, we should consider thinking about the correct structure of them, as the current approach for the alpha became a bit messy.

**Comment by roschaefer** [comment]
Translation files in a .json are inherently messy. Can we please add them immediately?

**Comment by appinteractive** [comment]
Don’t get what you mean. And yes I will be on it at Monday

**Comment by roschaefer** [comment]
I was just saying that, regardless how hard we try, they will geht messy in the end. Maybe there is some best practice on the web but I can't remember any project where people did not complain about the structure of the translations at least once.

**Comment by appinteractive** [comment]
It’s not so Problem of json, it’s a problem of translations in general. You rip apart a layer of the application and start wondering after a while what belongs where. But for that we have tools like lokalize to manage that.

**Comment by appinteractive** [comment]
Will Setup the pipeline next week
