### ISSUE TITLE
Editor - TipTap Editor

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#121]
We want to add the TipTap instead of the Quill editor as it is easier to write vue components with it and its easier to extend.

https://github.com/scrumpy/tiptap

**Comment by roschaefer** [comment]
duplicate #119

**Comment by appinteractive** [comment]
Why are you closing this @roschaefer ? It’s an epic not an issue so it’s not duplicated. I think we need to discuss the use of epics. 🤨
