### ISSUE TITLE
Mobile friendlyness

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#122]
As a user
I would like to see posts in full with on my mobile
In order to be able to read comfortably on the go

A first step could be to wrap the navigation to the top of the post when on mobile (see styleguide)
The best option would be a floating menu which expands on press while on mobile.
Do you have an even better idea to solving that?

Current State:
![Bildschirmfoto 2019-01-07 um 18.21.33.png](https://images.zenhubusercontent.com/5bd85e194961020970cde7d4/0cc20b20-bf13-4860-8a75-ee1494a7877a)

**Comment by appinteractive** [comment]
To fix the issue, set the `:with` proprty on both `flex-item` elements, see the `profile/_slug.vue` for reference.

**Comment by Kachulio1** [comment]
@appinteractive should I put the menu nav above or it's ok like that.
<img width="543" alt="screen shot 2019-01-22 at 01 52 23" src="https://user-images.githubusercontent.com/22243090/51502828-eef28480-1de8-11e9-8801-7eb214e3b30a.png">

**Comment by roschaefer** [comment]
@Kachulio1 for me it's also OK to type the URL by hand for now. We can decided on the Navigation later. :slightly_smiling_face:

**Comment by Kachulio1** [comment]
LOL

**Comment by appinteractive** [comment]
Below should be fine for now. Later we will add a better solution that’s more mobile friendly.

**Comment by Kachulio1** [comment]
ok 👍
