### ISSUE TITLE
Travis CI: Fix checked out branch of backend

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Nitro-Web#128]
**Describe the bug**
For fullstack testing we're currently trying to check out `TRAVIS_BRANCH` in the backend. If no such branch exists, we fall back to `master`. According to Travis CI specs the variable is the **target** branch for pull requests, which would be `master` in most cases. That's not what we want.

See here: https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**To Reproduce**
Submit a pull request that relies on a change in the backend. Most likely, the push build succeeds but the PR build fails.

**Expected behavior**
Both push and PR build should succeed.

**Additional context**
Fortunately, Travis has yet another environment variable for the base branch `TRAVIS_PULL_REQUEST_BRANCH`. So, a possible solution is to:
1. Save `TRAVIS_PULL_REQUEST_BRANCH || TRAVIS_BRANCH` in a variable in that order.
2. Try to check out the above branch from the backend, fall back to `master` if no such branch exists.

**Comment by appinteractive** [comment]
@roschaefer it was fixed correct?
