### ISSUE TITLE
Add a language version for British English

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Nitro-Web#133]
**Is your feature request related to a problem? Please describe.**
The current English version of the UI covers American English only. There is no version for British English.

**Describe the solution you'd like**
- Add a version for British English on Lokalise
- Rename current English version for the UI to -> English (US)
- Add a language version for the UI for British English -> English (UK)

This affects Lokalise and the UI but not the preference/filter setting for contributions.

**Comment by roschaefer** [comment]
@sushidave I double-checked on [lokalise](https://lokalise.co/project/556252725c18dd752dd546.13222042/) and found out that we indeed have localized versions of some languages:
![Screenshot (46)](https://user-images.githubusercontent.com/2110676/54995129-52a25500-4fc6-11e9-84af-8e595df7b9d6.png)

But I would like to [keep-it-simple-stupid](https://en.wikipedia.org/wiki/KISS_principle) and just have one unspecific language version for now.

Are you OK with that? If not, feel free to reopen this issue [here](https://github.com/Human-Connection/Human-Connection/issues). :+1:
