### ISSUE TITLE
ThemeLandMap

### ISSUE THREAD

**Issue by kuerzi** [Human-Connection/Nitro-Web#15]
As a user i want a zoomable overview over all Themes and Posts (without private Information of users)
kind of like 
graph databank itself 
or like the "Spiegel Mining" https://media.ccc.de/v/33c3-7912-spiegelmining_reverse_engineering_von_spiegel-online#t=1375

or more like the Zoomable maps in Computergames 
like "For the Unity!" aka"Sins of a solar Empire" , "Planetary Annihilation" or "Ashes of the Singularity"
with Ram and CPU preserving zoom "Stages",
which summarize groups In Symbols, when its outzoomed 
in our example the filterselectors
and become more detailed when zooming in maybe visible hashtags and moods in middle Stage 
and most detailed the post itself (within its moods and Hashtags and Link references) when zoomed all in 
(maybe with visible Postimage only requested by hover over 1second & last zoom in Staage  or full zoomed in, to preserve frontend Resources)

I want this, 
because it is a far better user experience (and makes much more fun) 
then the swap up and down functionality of facebook 
where you must choose any competing asessment criteria (e.g newest, oldest, most rated, ...)

For highlighting can dos which are only able for a short ammount of time 
e.g. at a certain date or looking for recently posts from a certain time 
an additive "highlight timespan" timeline functionality would be good too

**Comment by kuerzi** [comment]
Its also good to have this for later calculations against bots and against assimilation attacks 
and to support the moderators.

**Comment by roschaefer** [comment]
@kuerzi thanks for your issue but it's not quite clear to me what the problem-to-be-solved is here.

I like graph visualizations but I don't know if a visualization of all users might be a little out of scope for our network. Anybody can still access the backend through this [endpoint](https://nitro-staging.human-connection.org/api) and generate the visualization offline for journalism and research.

What do you think about that?

@kuerzi I'm migrating all issues over to [here](https://github.com/Human-Connection/Human-Connection/issues) so if you think it is still an issue, feel free to reopen it there.
