### ISSUE TITLE
Running the test with --watch flag does not work

### ISSUE THREAD

**Issue by Kachulio1** [Human-Connection/Nitro-Web#171]
**Describe the bug**
When you run `yarn test --watch` you get an error

**Screenshots**
<img width="548" alt="screen shot 2019-02-07 at 20 03 55" src="https://user-images.githubusercontent.com/22243090/52429034-55c7ab80-2b14-11e9-8d7f-7b9669b38ed3.png">

**Suggested Solution** 
if you remove the tilde in `moduleNameMapper` it works.
<img width="508" alt="screen shot 2019-02-07 at 20 12 46" src="https://user-images.githubusercontent.com/22243090/52429325-e30b0000-2b14-11e9-9366-46b9d4f2a8bd.png">

**Comment by roschaefer** [comment]
PR please! :+1:

**Comment by appinteractive** [comment]
Is it then still working for the rest of the application? I’m afraid of side effects with that.

**Comment by Kachulio1** [comment]
This is weird, after removing that tilde and run the test with watch and then put it back, there is no error.

**Comment by Kachulio1** [comment]
@appinteractive @roschaefer if you run test with --watch are you getting that error

**Comment by Kachulio1** [comment]
@mattwr18 has the same
 error.

**Comment by roschaefer** [comment]
![2019-03-26-130810_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/54995816-f9d3bc00-4fc7-11e9-8cc2-2cc610937f47.png)

This is what `yarn run test --watch` gives me in folder `/webapp`. I think this can be closed.
