### ISSUE TITLE
[Post] Shout button does not function correct

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Web#201]
**Describe the bug**
Shout button on the post page does not function correctly.
Wrongly named in German `Empfohlen`. Add localisation.

**To Reproduce**
1. Run the `master` branch. Go to 'http://127.0.0.1:3000/'
2. Go on a post
3. Click on `Shout` button, wrongly named in German `Empfohlen`
4. It increases one and `Shout` button gets inactive
5. Click on the right menu on `More`
6. Change back to `Post` in the same menu
7. You find the `Shout` button active and if you click on it increases again, what is both an error

**Expected behavior**
`↓ load more` button disappears or gets inactive.

**Screenshots**

See screenshot 1:
<img width="1703" alt="bildschirmfoto 2019-02-26 um 17 14 27" src="https://user-images.githubusercontent.com/25344101/53428887-dc70f980-39eb-11e9-8c14-329649b4ce12.png">

See screenshot 2:
<img width="1703" alt="bildschirmfoto 2019-02-26 um 17 29 43" src="https://user-images.githubusercontent.com/25344101/53429043-278b0c80-39ec-11e9-9f94-136fb008107c.png">

See screenshot 3:
<img width="1703" alt="bildschirmfoto 2019-02-26 um 17 14 42" src="https://user-images.githubusercontent.com/25344101/53428904-e692f800-39eb-11e9-9c1b-1f9144aaa1d0.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari
 - Version 12.0.2

**Comment by appinteractive** [comment]
Seed https://github.com/Human-Connection/Nitro-Web/issues/201

**Comment by Tirokk** [comment]
Hey, super! I will have a look later!
