### ISSUE TITLE
[Internationalization] Put all not translated texts here or wrong translations as well 

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Web#202]
**Post Page**
Shout button: In Language EN still has text in German `Empfohlen`

**Screenshot**
![53431592-1d1f4180-39f1-11e9-845a-84fa1225b36c](https://user-images.githubusercontent.com/432828/53696430-38aa9380-3dc7-11e9-8990-8d41f63563bd.png)

**Comment by roschaefer** [comment]
@Tirokk I hope you don't mind but I would like to close this. We have to do more code reviews and for the existing untranslated strings I would suggest to fix it along the way.
