### ISSUE TITLE
Replace the Nitro-green into an Alpha-green

### ISSUE THREAD

**Issue by mirella-fortunato** [Human-Connection/Nitro-Web#223]
The green color used in the Nitro is not the same as in the the Alpha version.

**Comment by appinteractive** [comment]
Yeah for good reason, at first there is no one green but many as the logo suggest. 
Second, the alpha green tends to be very aggressive on some displays and nearly  non existent on projectors. Also is the Accessibility for visually impaired persons not the best as the contrast on white is not that good. Therefore we use a darker shade for the nitro to enhance the previous points.

**Comment by roschaefer** [comment]
@mirella-fortunato thank you so much for your feature request! It is so great that you found your way on Github. :tada:  We enjoy if our users pro-actively request features or report bugs here.

In this very case I cannot say much about the accessibility of colours, so I simply trust @appinteractive who has better sensitivity here.

However, you can request more features on Github. By telling what problem needs to be solved, you can help us a little to find a good solution for it.

**Comment by appinteractive** [comment]
Thanks @mirella-fortunato also from me, hope that you did not misunderstood my comment, I was writing ✍️ it on the run 🏃

If you have more arguments, feel free to share it here!

**Comment by mirella-fortunato** [comment]
@appinteractive @roschaefer 

Hey!
thank you for your feedback. 
I try to be clear and simple in what i recognize as a bug or mistake,
but i'm a bit insecure about the explanations i can give and don't know much about the work you are doing.
So, please aske me, if you don't know what i exactly try to say.
I'll try my best.

**Comment by roschaefer** [comment]
Ok, I have the feeling this issue is resolved, no? If not feel free to reopen.
