### ISSUE TITLE
Translate all terms in the different languages

### ISSUE THREAD

**Issue by mirella-fortunato** [Human-Connection/Nitro-Web#224]
Not all terms are translated and emplemented in the different languages on the users side.

In the network frame: 
-title (Netzwerk)
-whom follows the user
-who follows the user

Settings:
-Your Name
-Your City or Region
-About You

**Comment by appinteractive** [comment]
Please take a look here: https://lokalise.co/public/556252725c18dd752dd546.13222042/

**Comment by mirella-fortunato** [comment]
@appinteractive 
Thank you for the link.
I quess it means that you are working on the translations.
If you need people for the translation process, than let me know.
I can try to find some user of HC that are nativ speakers of the different languages.

**Comment by appinteractive** [comment]
You can actually participate under that link! And yeah just let them come 😊👍

**Comment by roschaefer** [comment]
@mirella-fortunato we're moving the entire code base into a single repo and I'm moving issues from [Nitro-Web](https://github.com/Human-Connection/Nitro-Web) to [Human-Connection](https://github.com/Human-Connection/Human-Connection) and I have to decide what to do with issues.

After you learned we have a translation service for this, are you OK to close this? If not, feel free to reopen [here](https://github.com/Human-Connection/Human-Connection/issues).
