### ISSUE TITLE
Proxy well-kown path to right backend path

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/Nitro-Web#271]
From the frontend the requests to the `/.well-known` path should all be proxied to the right backend path.  

@roschaefer a question comes to my mind. Why to the backend? In the frontend it's possible to use something like [webfinger.js](https://www.npmjs.com/package/webfinger.js?__hstc=72727564.e835c34ab7bf88e972fdd7a7debc8575.1426032000053.1426032000054.1426032000055.1&__hssc=72727564.7.1426032000056&__hsfp=59720947) [webfinger](https://www.npmjs.com/package/webfinger) to lookup profiles from other instances. The /.well-known/webfinger endpoint is for other servers to lookup our actors.

**Comment by Mastercuber** [comment]
Maybe we could also implement a post method for the `/.well-known/webfinger` router to handle the search for a user also in the activityPub component.

**Comment by roschaefer** [comment]
closed via https://github.com/Human-Connection/Human-Connection/pull/243/files
