### ISSUE TITLE
Core-Feature: Full text search in top bar

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Nitro-Web#37]
As a user 
I'd like to search for specific words 
in order to find related content

**Comment by faithngetich** [comment]
@datenbrei specific words in the post or what words are you interested in searching?

**Comment by roschaefer** [comment]
If possible: Author, Post content, Post title, Tags, Categories

**Comment by Tirokk** [comment]
Should the search go like this @roschaefer @datenbrei :
(A bit similar to Google-Search.)

- If the search field contains one word (no space) then search this as part of the posts fields you mentioned. ("Part of" means as an example: Search of „world“ also finds „worlds“ etc. in the post.)
- If there are more than one words in the search field (separated by space(s)) then search all these words as parts of the posts.
- If a phrase (more than one word separated by space(s)) is written in ““ it should be seen as one word.
- Priority: As higher the priority score as more further the resulting post shall be in the search list.
- Priority 1 (highest score): All the words or the most of them are in the same sequence as in the search field.
- Priority 2 (second highest score): As more often the same word is in the post.
- Priority X: Any other ideas?

**Comment by roschaefer** [comment]
@Tirokk I would say: Let's [KISS](https://en.wikipedia.org/wiki/KISS_principle) :kissing_heart: Keep It Simple Stupid. If we can send a word to the backend and get all posts containing this word in the content or title field, this is step 1. We can iterate from there and make the search more complex.

**Comment by Tirokk** [comment]
😘 It’s future thinking. At first we [KISS](https://en.wikipedia.org/wiki/KISS_principle) and than it can get more complicated. 🤗 ^^
