### ISSUE TITLE
Using LernaJS for Code splitting?

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#5]
LernaJS is a package that gives you the power to split your code into modules and maintain them in an easy way. Maybe we should try to use it to split out the style guide part!?

https://lernajs.io/

**Comment by Lulalaby** [comment]
looks nice 😄

**Comment by roschaefer** [comment]
I like the current setup that we publish the styleguide as a separate plugin, so I'm closing this. If anybody sees an advantage of using LernaJS over the status quo, feel free to reopen [here](https://github.com/Human-Connection/Human-Connection/issues).
