### ISSUE TITLE
Fix authentication 

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#7]
We need to request the user from the api on EVERY SSR to avoid inconsistencies that we have now as the token data does not change on user updates. 

This issue can be observed when chaning the own user data in the pr here: https://github.com/Human-Connection/Nitro-Web/pull/9

The values will return to the values at login time as we extract them from the JWT Token but does not update them in any way.

**Comment by roschaefer** [comment]
@appinteractive I don't get it

**Comment by appinteractive** [comment]
@roschaefer did you try it with the pr mentioned in the description?

**Comment by appinteractive** [comment]
This issue is solved in https://github.com/Human-Connection/Nitro-Web/pull/9

**Comment by roschaefer** [comment]
But this issue is not tested in #9

**Comment by appinteractive** [comment]
Tests are written right now @roschaefer , still a WIP, thats why this one is still open.

**Comment by appinteractive** [comment]
Is (integration)tested and fixed
