### ISSUE TITLE
[Internationalization] - Integrate Lokalise.co pipeline

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#72]
We need to integrate and setup [lokalise.co](http://lokalise.co) for a better translation workflow and management.

Als do we have to add some mention of lokalise.co on our readme.

**Comment by roschaefer** [comment]
I think this is the perfect issue for @mattwr18, what do you think?

**Comment by appinteractive** [comment]
You Need github Admin rights and the same for lokalise.

**Comment by roschaefer** [comment]
@mattwr18 we can give you admin powers for lokalise, interested?

**Comment by mattwr18** [comment]
hey sorry, I saw this, but didn't respond and forgot about the comments...
I would be interested in working on this when I can be given access

**Comment by appinteractive** [comment]
It’s basically done already.

**Comment by appinteractive** [comment]
Close #99
