### ISSUE TITLE
make profile streams a single column layout

### ISSUE THREAD

**Issue by oliverzet** [Human-Connection/Nitro-Web#73]
Currently the profile page streams are divided into two columns. This causes some problems in desktop as well as in mobile view. Additionally the two column layout doesn't seem to provide any benefits to the user experience.

**Mobile view**:

- The two-column view of posts on mobile devices makes the presentation too small and cluttered. 

- Labels like "Post" or "Can Do" hide parts of the user name on posts.

Example picture: https://drive.google.com/file/d/1r8cZg-UmE9FuOf7SM5ntc0gBgCKtWxCm/view?usp=sharing

**Desktop and mobile view**:

- Labels like "Post" or "Can Do", on posts in the left column, occasionally cover elements of the post. If you mouse over such a post, the element will burst through the label.

Example picture: https://drive.google.com/file/d/1XtzAlD-GSRp0W4nYiNGJa3sv4MNIUbRR/view?usp=sharing

**A possible solution** to all of these problems is, at least in my opinion, to get rid of the second column and make all profile streams (contributions, commented, shouted) a single column layout.

**Comment by appinteractive** [comment]
In Nitro its already fixed

<img width="1208" alt="bildschirmfoto 2018-12-10 um 16 15 19" src="https://user-images.githubusercontent.com/432828/49741513-e14cc980-fc96-11e8-9fb0-6e2d1c5e9180.png">
<img width="766" alt="bildschirmfoto 2018-12-10 um 16 15 33" src="https://user-images.githubusercontent.com/432828/49741514-e14cc980-fc96-11e8-9820-e9f3a8cdb473.png">

**Comment by oliverzet** [comment]
It probably is @appinteractive 
There don't seem to be any labels marking the postings as "Post" or "Can Do". Is this because it's a very early version of Nitro or aren't labels coming back?

**Comment by appinteractive** [comment]
@oliverzet yeah it’s because we only have posts at the moment. So the Ticket can be closed?

**Comment by appinteractive** [comment]
Sure it can be reopened when needed. A staging of the new system will be deployed the next days.
