### ISSUE TITLE
Improve Styleguide (integration)

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#8]
Currently the Stylguide is not nice to use as we have to build it every time when we change a component inside it to reflect the changes in the development process. 

Maybe we could use #5 to improve on that. We have to investigate the best option(s) for this.

**Comment by appinteractive** [comment]
@visualjerk would you maybe have some time to help us with a cleaner implementation of the styleguide?

**Comment by visualjerk** [comment]
Hey there! Have you already tried the approach outlined [here](https://github.com/visualjerk/vue-cion-design-system/wiki/Integration-with-Hot-Reloading#vue-cli)?

While the steps are not specifically written for Nuxt, it shouldn't be too complicated to adapt them to be used there.

**Comment by visualjerk** [comment]
Closed by #55
