### ISSUE TITLE
Reduce docker image size with multistage builds

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#93]
Currently the image of `Nitro-Web` way too large (314MB). Many build dependencies are included which are irrelevant for production.

![download 6](https://user-images.githubusercontent.com/2110676/50055001-24041b00-0149-11e9-87ea-710c73c5fc4c.png)

We would like to slim down the image size with multistage builds. We did that for the backend recenlty and the image size was reduced from >200MB to 110MB.
You can have a look into the Dockerfile of the backend to ~copy+paste~ get some inspiration:
https://github.com/Human-Connection/Nitro-Backend/blob/master/Dockerfile

**Comment by roschaefer** [comment]
I don't think multi stages will speed up the build, it rather slows it down.

A duration of 4:20 minutes is spent on building the image. I think the styleguide is a great pick for optimization.

**Comment by appinteractive** [comment]
That’s why I mentioned caching. It seams that  currently no caching is in place at all. We need to wire docker, npm and yarn caching to speed things up.

**Comment by roschaefer** [comment]
Can we distinguish between image size and build server speed?

I will rephrase this issue to match the image size for now. We can open another one to try out caching on the build server and see if that speeds up the build.

**Comment by appinteractive** [comment]
902MB Whaaaaaaaa? I guess thast mostly dev dependencies as we did not add any big stuff on the frontend since. The Fight against the Bytes shell begin... :)
