### ISSUE TITLE
Invalid signature error

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Nitro-Web#95]
**Describe the bug**
When I previously logged in to our `nitro-staging` environment at https://nitro-staging.human-connection.org/ and re-visit the site, I see a "Invalid Signature" error.

**To Reproduce**
1. Log in to https://nitro-staging.human-connection.org/
2. Wait for a day or so
3. Go to https://nitro-staging.human-connection.org/ again
![download 7](https://user-images.githubusercontent.com/2110676/50102876-8d0d9080-0226-11e9-83f0-82c64052e087.png)

**Expected behavior**
I should see the login screen again.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version 71.0.3578.98

**Comment by appinteractive** [comment]
@roschaefer do you need help with that?

**Comment by roschaefer** [comment]
Potentially yes, but I would like to reproduce the errors with tests! See #98
